branches:
  - main

tagFormat: "${version}"

preset: "conventionalcommits"

plugins:
  - '@semantic-release/commit-analyzer'
  -
    - "@semantic-release/release-notes-generator"
    - host: "https://github.com"
  -
    - "@semantic-release/git"
    - assets: []
      messsage: false
  -
    - "@semantic-release/github"
    - successComment: false
      failComment: false
  -
    - "@semantic-release/exec"
    - verifyConditionsCmd: "rm -rf *.tgz"
      prepareCmd: "helm package --version ${nextRelease.version} . && helm chart save schemahero-${nextRelease.version}.tgz ghcr.io/eshepelyuk/helm/schemahero:${nextRelease.version}"
      publishCmd: "helm chart push ghcr.io/eshepelyuk/helm/schemahero:${nextRelease.version}"
