apiVersion: v1
kind: Service
metadata:
  name: {{ include "schemahero.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "schemahero.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webhook
      protocol: TCP
  selector:
    {{- include "schemahero.selectorLabels" . | nindent 4 }}
