name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '*.puml'
      - '.releaserc.yaml'
      - 'package*.json'
      - '.*ignore'
      - '.github/workflows/release.yaml'

jobs:
  ci_job:
    name: Continous integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: volesen/setup-skaffold@v1.1
        with:
          version: 'v1.32.0'
      - uses: bahmutov/npm-install@v1.10.10
      - name: Run commit linter
        run: |
          npx semantic-release -p semantic-release-commitlint
      - name: Run Helm linter
        run: |
          ./test/lint/run.sh
      - name: Start K8s
        uses: AbsaOSS/k3d-action@v2.4.0
        with:
          k3d-version: v5.8.3
          cluster-name: "k3d"
          args: >-
            --config ./test/e2e/k3d.yaml
      - name: Start PostgreSQL
        run: |
          helm install --wait --version 16.7.27 pgsql oci://registry-1.docker.io/bitnamicharts/postgresql \
            --set auth.postgresPassword=postgres \
            --set primary.persistence.enabled=false
      - name: Setup local Docker registry
        run: |
          k3d registry create localhost --port 5000
          skaffold config set default-repo localhost:5000
      - name: Build e2e tests
        run: |
          skaffold build
      - name: Deploy SchemaHero Helm chart
        run: |
          skaffold run
      - name: Run e2e tests
        run: |
          helm test sch --logs --timeout 1m30s
