name: Release

on:
  workflow_dispatch

env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  release_job:
    name: Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to GitHub Packages
        run: |
          helm registry login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GHCR_TOKEN }}
      - uses: bahmutov/npm-install@v1.7.7
      - name: Semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
